# Generated by Django 4.1.4 on 2022-12-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Specialtopic', '0007_system_database_system_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_database',
            name='USN',
            field=models.CharField(max_length=11),
        ),
    ]
